using System.Collections.Generic;

namespace MalumMenu
{
    public static class Localization
    {
        public static string CurrentLanguage
        {
            get => MalumMenu.selectedLanguage.Value;
            set => MalumMenu.selectedLanguage.Value = value;
        }

        private static readonly Dictionary<string, Dictionary<string, string>> translations = new()
        {
            ["en"] = new Dictionary<string, string>
            {
                ["Language"] = "Language",
                ["Player"] = "Player",
                [" NoClip"] = " NoClip",
                [" SpeedHack"] = " SpeedHack",
                ["Teleport"] = "Teleport",
                [" to Cursor"] = " to Cursor",
                [" to Player"] = " to Player",

                ["ESP"] = "ESP",
                ["See Roles"] = "See Roles",
                ["See Ghosts"] = "See Ghosts",
                ["No Shadows"] = "No Shadows",
                ["Reveal Votes"] = "Reveal Votes",
                ["Camera"] = "Camera",
                ["Zoom Out"] = "Zoom Out",
                ["Spectate"] = "Spectate",
                ["Freecam"] = "Freecam",
                ["Tracers"] = "Tracers",
                [" Crewmates"] = " Crewmates",
                [" Impostors"] = " Impostors",
                [" Ghosts"] = " Ghosts",
                [" Dead Bodies"] = " Dead Bodies",
                [" Color-based"] = " Color-based",
                ["Minimap"] = "Minimap",

                ["Roles"] = "Roles",
                [" Set Fake Role"] = " Set Fake Role",
                ["Impostor"] = "Impostor",
                [" Kill Reach"] = " Kill Reach",
                ["Shapeshifter"] = "Shapeshifter",
                [" No Ss Animation"] = " No Ss Animation",
                [" Endless Ss Duration"] = " Endless Ss Duration",
                ["Crewmate"] = "Crewmate",
                [" Complete My Tasks"] = " Complete My Tasks",
                ["Tracker"] = "Tracker",
                [" Endless Tracking"] = " Endless Tracking",
                [" No Track Delay"] = " No Track Delay",
                [" No Track Cooldown"] = " No Track Cooldown",
                ["Engineer"] = "Engineer",
                [" Endless Vent Time"] = " Endless Vent Time",
                [" No Vent Cooldown"] = " No Vent Cooldown",
                ["Scientist"] = "Scientist",
                [" Endless Battery"] = " Endless Battery",
                [" No Vitals Cooldown"] = " No Vitals Cooldown",

                ["Ship"] = "Ship",
                ["Unfixable Lights"] = "Unfixable Lights",
                ["Report Body"] = "Report Body",
                ["Close Meeting"] = "Close Meeting",
                ["Sabotage"] = "Sabotage",
                ["Reactor"] = "Reactor",
                ["Oxygen"] = "Oxygen",
                ["Lights"] = "Lights",
                ["Comms"] = "Comms",
                ["Doors"] = "Doors",
                ["MushroomMixup"] = "MushroomMixup",
                ["Vents"] = "Vents",
                [" Unlock Vents"] = " Unlock Vents",
                [" Kick All From Vents"] = " Kick All From Vents",
                [" Walk In Vents"] = " Walk In Vents",

                ["Chat"] = "Chat",
                [" Enable Chat"] = " Enable Chat",
                [" Unlock Textbox"] = " Unlock Textbox",

                ["Host-Only"] = "Host-Only",
                ["Kill While Vanished"] = "Kill While Vanished",
                ["Kill Anyone"] = "Kill Anyone",
                ["No Kill Cooldown"] = "No Kill Cooldown",
                ["Murder"] = "Murder",
                ["Kill Player"] = "Kill Player",
                ["Kill All Crewmates"] = "Kill All Crewmates",
                ["Kill All Impostors"] = "Kill All Impostors",
                ["Kill Everyone"] = "Kill Everyone",

                ["Passive"] = "Passive",
                [" Free Cosmetics"] = " Free Cosmetics",
                [" Avoid Penalties"] = " Avoid Penalties",
                [" Unlock Extra Features"] = " Unlock Extra Features",
            },

            ["ko"] = new Dictionary<string, string>
            {
                ["Language"] = "언어",
                ["Player"] = "플레이어",
                [" NoClip"] = " 노클립",
                [" SpeedHack"] = " 스피드핵",
                ["Teleport"] = "텔레포트",
                [" to Cursor"] = " 커서로 이동",
                [" to Player"] = " 플레이어에게 이동",

                ["ESP"] = "ESP",
                ["See Roles"] = "역할 보기",
                ["See Ghosts"] = "유령 보기",
                ["No Shadows"] = "그림자 없음",
                ["Reveal Votes"] = "투표 공개",
                ["Camera"] = "카메라",
                ["Zoom Out"] = "줌 아웃",
                ["Spectate"] = "관전",
                ["Freecam"] = "자유 시점",
                ["Tracers"] = "추적선",
                [" Crewmates"] = " 크루원",
                [" Impostors"] = " 임포스터",
                [" Ghosts"] = " 유령",
                [" Dead Bodies"] = " 시체",
                [" Color-based"] = " 색상 기반",
                ["Minimap"] = "미니맵",

                ["Roles"] = "역할",
                [" Set Fake Role"] = " 가짜 역할 설정",
                ["Impostor"] = "임포스터",
                [" Kill Reach"] = " 킬 범위 증가",
                ["Shapeshifter"] = "변신자",
                [" No Ss Animation"] = " 변신 애니메이션 없음",
                [" Endless Ss Duration"] = " 무한 변신 지속시간",
                ["Crewmate"] = "크루원",
                [" Complete My Tasks"] = " 내 작업 완료",
                ["Tracker"] = "추적자",
                [" Endless Tracking"] = " 무한 추적",
                [" No Track Delay"] = " 추적 지연 없음",
                [" No Track Cooldown"] = " 추적 쿨다운 없음",
                ["Engineer"] = "엔지니어",
                [" Endless Vent Time"] = " 무한 벤트 시간",
                [" No Vent Cooldown"] = " 벤트 쿨다운 없음",
                ["Scientist"] = "과학자",
                [" Endless Battery"] = " 무한 배터리",
                [" No Vitals Cooldown"] = " 바이탈 쿨다운 없음",

                ["Ship"] = "우주선",
                ["Unfixable Lights"] = "수리 불가능한 조명",
                ["Report Body"] = "시체 신고",
                ["Close Meeting"] = "회의 닫기",
                ["Sabotage"] = "사보타지",
                ["Reactor"] = "리액터",
                ["Oxygen"] = "산소",
                ["Lights"] = "조명",
                ["Comms"] = "통신",
                ["Doors"] = "문",
                ["MushroomMixup"] = "버섯 혼란",
                ["Vents"] = "벤트",
                [" Unlock Vents"] = " 벤트 열기",
                [" Kick All From Vents"] = " 모두 벤트에서 추방",
                [" Walk In Vents"] = " 벤트에서 걷기",

                ["Chat"] = "채팅",
                [" Enable Chat"] = " 채팅 활성화",
                [" Unlock Textbox"] = " 텍스트박스 잠금 해제",

                ["Host-Only"] = "호스트 전용",
                ["Kill While Vanished"] = "사라진 상태로 킬",
                ["Kill Anyone"] = "모두 킬 가능",
                ["No Kill Cooldown"] = "킬 쿨다운 없음",
                ["Murder"] = "살해",
                ["Kill Player"] = "플레이어 죽이기",
                ["Kill All Crewmates"] = "모든 크루원 죽이기",
                ["Kill All Impostors"] = "모든 임포스터 죽이기",
                ["Kill Everyone"] = "모두 죽이기",

                ["Passive"] = "패시브",
                [" Free Cosmetics"] = " 무료 코스메틱",
                [" Avoid Penalties"] = " 페널티 회피",
                [" Unlock Extra Features"] = " 추가 기능 잠금 해제",
            },

            ["ru"] = new Dictionary<string, string>
        {
            ["Language"] = "Язык",
            ["Player"] = "Игрок",
            [" NoClip"] = " Noclip",
            [" SpeedHack"] = " Ускорить Игрока",
            ["Teleport"] = "Телепорт",
            [" to Cursor"] = " к курсору",
            [" to Player"] = " к игроку",

            ["ESP"] = "ESP",
            ["See Roles"] = "Показать Роли",
            ["See Ghosts"] = "Показать Призраков",
            ["No Shadows"] = "Убрать Тени",
            ["Reveal Votes"] = "Показать Голоса",
            ["Camera"] = "Камера",
            ["Zoom Out"] = "Отдалить",
            ["Spectate"] = "Наблюдать",
            ["Freecam"] = "Свободная Камера",
            ["Tracers"] = "Трейсеры",
            [" Crewmates"] = " Члены Экипажа",
            [" Impostors"] = " Предатели",
            [" Ghosts"] = " Призраки",
            [" Dead Bodies"] = " Трупы",
            [" Color-based"] = " По Цвету",
            ["Minimap"] = "Миникарта",

            ["Roles"] = "Роли",
            [" Set Fake Role"] = " Установить Фейковую Роль",
            ["Impostor"] = "Предатель",
            [" Kill Reach"] = " Дальность Убийства",
            ["Shapeshifter"] = "Оборотень",
            [" No Ss Animation"] = " Без Анимации Смены Маскировки",
            [" Endless Ss Duration"] = " Бесконечная Длительность Маскировки",
            ["Crewmate"] = "Член Экипажа",
            [" Complete My Tasks"] = " Завершить Мои Задания",
            ["Tracker"] = "Следопыт",
            [" Endless Tracking"] = " Бесконечная Слежка",
            [" No Track Delay"] = " Без Задержки Отслеживания",
            [" No Track Cooldown"] = " Без Перезарядки Отслеживания",
            ["Engineer"] = "Инженер",
            [" Endless Vent Time"] = " Бесконечное Время в Люках",
            [" No Vent Cooldown"] = " Без Перезарядки Люков",
            ["Scientist"] = "Ученый",
            [" Endless Battery"] = " Бесконечная батарея",
            [" No Vitals Cooldown"] = " Без Перезарядки Панели Проверки Пульса",

            ["Ship"] = "Корабль",
            ["Unfixable Lights"] = "Неисправимый Свет",
            ["Report Body"] = "Сообщить о Теле",
            ["Close Meeting"] = "Закрыть Cобрание",
            ["Sabotage"] = "Саботаж",
            ["Reactor"] = "Реактор",
            ["Oxygen"] = "Кислород",
            ["Lights"] = "Свет",
            ["Comms"] = "Связь",
            ["Doors"] = "Двери",
            ["MushroomMixup"] = "Грибной Переполох",
            ["Vents"] = "Люки",
            [" Unlock Vents"] = " Открыть люки",
            [" Kick All From Vents"] = " Выгнать Всех из Люков",
            [" Walk In Vents"] = " Ходить в Люках",

            ["Chat"] = "Чат",
            [" Enable Chat"] = " Разблокировать Чат",
            [" Unlock Textbox"] = " Разблокировать Поле Ввода",

            ["Host-Only"] = "Только для Хоста",
            ["Kill While Vanished"] = "Убивать в Невидимости",
            ["Kill Anyone"] = "Убивать Любого",
            ["No Kill Cooldown"] = "Убрать Перезарядку Убийства",
            ["Murder"] = "Убийство",
            ["Kill Player"] = "Убить Игрока",
            ["Kill All Crewmates"] = "Убить Всех Членов Экипажа",
            ["Kill All Impostors"] = "Убить Всех Предателей",
            ["Kill Everyone"] = "Убить Всех",

            ["Passive"] = "Пассивные",
            [" Free Cosmetics"] = " Бесплатная Косметика",
            [" Avoid Penalties"] = " Избежать Наказаний",
            [" Unlock Extra Features"] = " Разблокировать доп. Функции",
        },
            
            ["zh-Hans"] = new Dictionary<string, string>
            {
                ["Language"] = "语言",
                ["Player"] = "玩家",
                [" NoClip"] = " 穿墙",
                [" SpeedHack"] = " 加速",
                ["Teleport"] = "传送",
                [" to Cursor"] = " 到光标",
                [" to Player"] = " 到玩家",

                ["ESP"] = "透视",
                ["See Roles"] = "显示角色",
                ["See Ghosts"] = "显示幽灵",
                ["No Shadows"] = "无阴影",
                ["Reveal Votes"] = "显示投票",
                ["Camera"] = "相机",
                ["Zoom Out"] = "缩小",
                ["Spectate"] = "观察",
                ["Freecam"] = "自由相机",
                ["Tracers"] = "追踪线",
                [" Crewmates"] = " 船员",
                [" Impostors"] = " 冒名者",
                [" Ghosts"] = " 幽灵",
                [" Dead Bodies"] = " 尸体",
                [" Color-based"] = " 按颜色",
                ["Minimap"] = "小地图",

                ["Roles"] = "角色",
                [" Set Fake Role"] = " 设置伪造角色",
                ["Impostor"] = "冒名者",
                [" Kill Reach"] = " 杀人距离",
                ["Shapeshifter"] = "变形者",
                [" No Ss Animation"] = " 无变形动画",
                [" Endless Ss Duration"] = " 无限变形时间",
                ["Crewmate"] = "船员",
                [" Complete My Tasks"] = " 完成我的任务",
                ["Tracker"] = "追踪者",
                [" Endless Tracking"] = " 无限追踪",
                [" No Track Delay"] = " 无追踪延迟",
                [" No Track Cooldown"] = " 无追踪冷却",
                ["Engineer"] = "工程师",
                [" Endless Vent Time"] = " 无限通风时间",
                [" No Vent Cooldown"] = " 无通风冷却",
                ["Scientist"] = "科学家",
                [" Endless Battery"] = " 无限电量",
                [" No Vitals Cooldown"] = " 无生命探测冷却",

                ["Ship"] = "飞船",
                ["Unfixable Lights"] = "无法修复的灯光",
                ["Report Body"] = "报告尸体",
                ["Close Meeting"] = "关闭会议",
                ["Sabotage"] = "破坏",
                ["Reactor"] = "反应堆",
                ["Oxygen"] = "氧气",
                ["Lights"] = "灯光",
                ["Comms"] = "通讯",
                ["Doors"] = "门",
                ["MushroomMixup"] = "蘑菇混乱",
                ["Vents"] = "通风口",
                [" Unlock Vents"] = " 解锁通风口",
                [" Kick All From Vents"] = " 将所有人踢出通风口",
                [" Walk In Vents"] = " 走进通风口",

                ["Chat"] = "聊天",
                [" Enable Chat"] = " 启用聊天",
                [" Unlock Textbox"] = " 解锁文本框",

                ["Host-Only"] = "仅限主机",
                ["Kill While Vanished"] = "隐身杀人",
                ["Kill Anyone"] = "杀任何人",
                ["No Kill Cooldown"] = "无冷却",
                ["Murder"] = "谋杀",
                ["Kill Player"] = "击杀玩家",
                ["Kill All Crewmates"] = "击杀所有船员",
                ["Kill All Impostors"] = "击杀所有冒名者",
                ["Kill Everyone"] = "击杀所有人",

                ["Passive"] = "被动",
                [" Free Cosmetics"] = " 免费装扮",
                [" Avoid Penalties"] = " 避免惩罚",
                [" Unlock Extra Features"] = " 解锁额外功能",
            },

            ["zh-Hant"] = new Dictionary<string, string>
            {
                ["Language"] = "語言",
                ["Player"] = "玩家",
                [" NoClip"] = " 穿牆",
                [" SpeedHack"] = " 加速",
                ["Teleport"] = "傳送",
                [" to Cursor"] = " 到游標",
                [" to Player"] = " 到玩家",

                ["ESP"] = "透視",
                ["See Roles"] = "顯示角色",
                ["See Ghosts"] = "顯示幽靈",
                ["No Shadows"] = "無陰影",
                ["Reveal Votes"] = "顯示投票",
                ["Camera"] = "攝影機",
                ["Zoom Out"] = "縮小",
                ["Spectate"] = "觀察",
                ["Freecam"] = "自由攝影機",
                ["Tracers"] = "追蹤線",
                [" Crewmates"] = " 船員",
                [" Impostors"] = " 冒名者",
                [" Ghosts"] = " 幽靈",
                [" Dead Bodies"] = " 屍體",
                [" Color-based"] = " 依顏色",
                ["Minimap"] = "小地圖",

                ["Roles"] = "角色",
                [" Set Fake Role"] = " 設定偽造角色",
                ["Impostor"] = "冒名者",
                [" Kill Reach"] = " 殺人距離",
                ["Shapeshifter"] = "變形者",
                [" No Ss Animation"] = " 無變形動畫",
                [" Endless Ss Duration"] = " 無限變形時間",
                ["Crewmate"] = "船員",
                [" Complete My Tasks"] = " 完成我的任務",
                ["Tracker"] = "追蹤者",
                [" Endless Tracking"] = " 無限追蹤",
                [" No Track Delay"] = " 無追蹤延遲",
                [" No Track Cooldown"] = " 無追蹤冷卻",
                ["Engineer"] = "工程師",
                [" Endless Vent Time"] = " 無限通風口時間",
                [" No Vent Cooldown"] = " 無通風口冷卻",
                ["Scientist"] = "科學家",
                [" Endless Battery"] = " 無限電量",
                [" No Vitals Cooldown"] = " 無生命探測冷卻",

                ["Ship"] = "飛船",
                ["Unfixable Lights"] = "無法修復的燈光",
                ["Report Body"] = "回報屍體",
                ["Close Meeting"] = "關閉會議",
                ["Sabotage"] = "破壞",
                ["Reactor"] = "反應爐",
                ["Oxygen"] = "氧氣",
                ["Lights"] = "燈光",
                ["Comms"] = "通訊",
                ["Doors"] = "門",
                ["MushroomMixup"] = "蘑菇混亂",
                ["Vents"] = "通風口",
                [" Unlock Vents"] = " 解鎖通風口",
                [" Kick All From Vents"] = " 將所有人踢出通風口",
                [" Walk In Vents"] = " 走入通風口",

                ["Chat"] = "聊天",
                [" Enable Chat"] = " 啟用聊天",
                [" Unlock Textbox"] = " 解鎖文字框",

                ["Host-Only"] = "僅限主機",
                ["Kill While Vanished"] = "隱身殺人",
                ["Kill Anyone"] = "殺任何人",
                ["No Kill Cooldown"] = "無冷卻",
                ["Murder"] = "謀殺",
                ["Kill Player"] = "殺死玩家",
                ["Kill All Crewmates"] = "殺死所有船員",
                ["Kill All Impostors"] = "殺死所有冒名者",
                ["Kill Everyone"] = "殺死所有人",

                ["Passive"] = "被動",
                [" Free Cosmetics"] = " 免費裝扮",
                [" Avoid Penalties"] = " 避免處罰",
                [" Unlock Extra Features"] = " 解鎖額外功能",
            },

            ["es"] = new Dictionary<string, string>
            {
                ["Language"] = "Idioma",
                ["Player"] = "Jugador",
                [" NoClip"] = " Sin clip",
                [" SpeedHack"] = " Aceleración",
                ["Teleport"] = "Teletransporte",
                [" to Cursor"] = " al cursor",
                [" to Player"] = " al jugador",

                ["ESP"] = "ESP",
                ["See Roles"] = "Ver roles",
                ["See Ghosts"] = "Ver fantasmas",
                ["No Shadows"] = "Sin sombras",
                ["Reveal Votes"] = "Revelar votos",
                ["Camera"] = "Cámara",
                ["Zoom Out"] = "Alejar",
                ["Spectate"] = "Espectador",
                ["Freecam"] = "Cámara libre",
                ["Tracers"] = "Trazadores",
                [" Crewmates"] = " Compañeros",
                [" Impostors"] = " Impostores",
                [" Ghosts"] = " Fantasmas",
                [" Dead Bodies"] = " Cuerpos",
                [" Color-based"] = " Por color",
                ["Minimap"] = "Minimapa",

                ["Roles"] = "Roles",
                [" Set Fake Role"] = " Establecer rol falso",
                ["Impostor"] = "Impostor",
                [" Kill Reach"] = " Alcance de muerte",
                ["Shapeshifter"] = "Cambiaformas",
                [" No Ss Animation"] = " Sin animación de cambio",
                [" Endless Ss Duration"] = " Duración infinita",
                ["Crewmate"] = "Compañero",
                [" Complete My Tasks"] = " Completar mis tareas",
                ["Tracker"] = "Rastreador",
                [" Endless Tracking"] = " Rastreo infinito",
                [" No Track Delay"] = " Sin demora de rastreo",
                [" No Track Cooldown"] = " Sin enfriamiento de rastreo",
                ["Engineer"] = "Ingeniero",
                [" Endless Vent Time"] = " Tiempo infinito en ventilación",
                [" No Vent Cooldown"] = " Sin enfriamiento de ventilación",
                ["Scientist"] = "Científico",
                [" Endless Battery"] = " Batería infinita",
                [" No Vitals Cooldown"] = " Sin enfriamiento de signos vitales",

                ["Ship"] = "Nave",
                ["Unfixable Lights"] = "Luces irreparables",
                ["Report Body"] = "Reportar cuerpo",
                ["Close Meeting"] = "Cerrar reunión",
                ["Sabotage"] = "Sabotaje",
                ["Reactor"] = "Reactor",
                ["Oxygen"] = "Oxígeno",
                ["Lights"] = "Luces",
                ["Comms"] = "Comunicaciones",
                ["Doors"] = "Puertas",
                ["MushroomMixup"] = "Caos de hongos",
                ["Vents"] = "Conductos",
                [" Unlock Vents"] = " Desbloquear conductos",
                [" Kick All From Vents"] = " Expulsar a todos del conducto",
                [" Walk In Vents"] = " Caminar en conductos",

                ["Chat"] = "Chat",
                [" Enable Chat"] = " Habilitar chat",
                [" Unlock Textbox"] = " Desbloquear cuadro de texto",

                ["Host-Only"] = "Solo anfitrión",
                ["Kill While Vanished"] = "Matar mientras está oculto",
                ["Kill Anyone"] = "Matar a cualquiera",
                ["No Kill Cooldown"] = "Sin enfriamiento de asesinato",
                ["Murder"] = "Asesinato",
                ["Kill Player"] = "Matar jugador",
                ["Kill All Crewmates"] = "Matar a todos los compañeros",
                ["Kill All Impostors"] = "Matar a todos los impostores",
                ["Kill Everyone"] = "Matar a todos",

                ["Passive"] = "Pasivo",
                [" Free Cosmetics"] = " Cosméticos gratis",
                [" Avoid Penalties"] = " Evitar penalizaciones",
                [" Unlock Extra Features"] = " Desbloquear funciones extra",
            },

        };

        public static string Translate(string key)
        {
            key = key.Trim();

            if (translations.TryGetValue(CurrentLanguage, out var langDict) &&
                langDict.TryGetValue(key, out var translation))
            {
                return translation;
            }

            return key; // Fallback if no translation found
        }
    }
}
